# -*- coding: utf-8 -*-

ru = {
    'ru_lang': 'Русский',
    'en_lang': 'English',
    'choose_lang_text': 'Выберите язык / Choose language',
    'hard_reise_alert_text': '<b>Создан сложный рейс</b>\n-----------------\nДата создания: <b>{date}</b>\nТелефон: <b>{phone}</b>\nКомментарий:\n{comment}',
    'hard_reise_btn': 'Сложный рейс #{booking_id}',
    'hard_reise_view': 'Сложный рейс #{booking_id}\n-----------------\nДата создания: <b>{date}</b>\nТелефон: <b>{phone}</b>\nКомментарий:\n{comment}',
    'hard_reise_cancel_view': '<b>Бронирование отменено</b>\nСложный рейс #{booking_id}\n-----------------\nДата создания: <b>{date}</b>\nТелефон: <b>{phone}</b>\nКомментарий:\n{comment}',
    'hard_reise_true_view': '<b>Бронирование подтверждено</b>\nСложный рейс #{booking_id}\n-----------------\nДата создания: <b>{date}</b>\nТелефон: <b>{phone}</b>\nКомментарий:\n{comment}',
    'user_id_btn': 'ID: {user}',
    'book_btn': '{dir_out} / {dir_in}',
    'rew_book_btn': '{dir_out} / {dir_in} / {dir_out}',
    'develop_message': 'Данный раздел находится в разработке',
    'book_one_direction_btn': 'В одну сторону',
    'book_two_direction_btn': 'Туда / обратно',
    'book_hard_direction_btn': 'Сложный рейс',
    'make_hard_reise_text': 'Отправьте сообщение с пожеланием какие бы вы рейсы хотели совершить',
    'hard_reise_meked_text': 'Запрос на сложный рейс создан, дождитесь ответа менеджера',
    'makebook_choise_menu': 'Бронирование на частный рейс\n-----------------\nВыберите вариант частного рейса',
    'lang_change_btn': 'ru / en',
    'alert_text': 'Напоминание о бронировании частного рейса\nДата вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nКоличество пассажиров: <b>{seats}</b>',
    'rew_alert_text': 'Напоминание о бронировании частного рейса\nДата вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nКоличество пассажиров: <b>{seats}</b>',
    'day': 'за день',
    'week': 'за неделю',
    'month': 'за месяц',
    'admin_stata_menu_text': 'Статистика <b>{period}</b>\n-----------------\nНовых бронирований: <b>{new_booking}</b>\nПодтверждено бронирований: <b>{true_booking}</b>\nВыполнено бронирований: <b>{done_booking}</b>\nОтменено бронирований: <b>{cancel_booking}</b>\nНовых заявок: <b>{new_ask}</b>\nВыполнено заявок: <b>{done_ask}</b>',
    'not_set': 'не установлена',
    'cancel_booking': 'Отменить бронирование',
    'edited': 'Отредактировано',
    'edit_date_fly_btn': 'Изменить дату вылета',
    'edit_date_fly_text': 'Отправьте сообщение с новой датой вылета',
    'edit_direction_out_btn': 'Изменить место вылета',
    'edit_direction_out_text': 'Отправьте сообщение с новым местом вылета',
    'edit_direction_btn': 'Изменить место назначения',
    'edit_direction_text': 'Отправьте сообщение с новым местом назначения',
    'edit_seats_btn': 'Изменить количество пассажиров',
    'edit_seats_text': 'Отправьте сообщение с новым количеством пассажиров',
    'edit_comment_btn': 'Добавить комментарий',
    'edit_comment_text': 'Отправьте сообщение с коментарием',
    'from_place_text': 'Отправьте сообщение с местом вылета',
    'two_from_place_text': 'Отправьте сообщение с местом вылета и возвращения',
    'to_direction_place_text': 'Отправьте сообщение с местом прибытия',
    'date_fly_text': 'Отправьте сообщение с датой вылета',
    'booking_message_text': 'Бронирование создано\nЖелаемая дата вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nКоличество пассажиров: <b>{seats}</b>\n-----------------\nБронирование создано, оператор свяжется с вами в течении часа',
    'rew_booking_message_text': 'Бронирование создано\nЖелаемая дата вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nКоличество пассажиров: <b>{seats}</b>\n-----------------\nБронирование создано, оператор свяжется с вами в течении часа',
    'booking_message_text_seats_error': 'Бронирование создано\nЖелаемая дата вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nТак как бот не смог распознать количество пассажиров, автоматически было установленно: <b>{seats}</b>\n-----------------\nБронирование создано, оператор свяжется с вами в течении часа',
    'fl_time_1-2': 'До 6 часов',
    'fl_time_3-5': 'От 6 до 9 часов',
    'fl_time_5-10': 'Свыше 9 часов',
    'error_message': 'Произошла ошибка',
    'reload_btn': 'Обновить',
    'view': 'Подробнее',
    'superadmin_menu_text': 'Добро пожаловать суперадмин',
    'su_admins_btn': 'Управление администраторами',
    'hiadmin': 'Привет админ {name}',
    'hello_message_reg_user': 'Вы можете забронировать частный рейс или посмотреть каталог самолетов',
    'hello_message': 'Спасибо за обращение в компанию Global Jet. Вы можете забронировать частный рейс или посмотреть каталог самолетов\n<b>{username}</b> пожалуйста пройдите процедуру регистрации.',
    'next': 'Вперед',
    'back': 'Назад',
    'plane_no_append': 'Самолет не назначен',
    'register': 'Регистрация',
    'edit_booking': 'Изменить бронирование',
    'yes_make_ask': 'Подтвердить заявку',
    'back_to_menu_btn': 'В меню',
    'reise': 'Частный рейс',
    'reise_down_menu': 'Выше показаны ваши заявки, для изменения бронирования на частный рейс нажмите кнопку "Изменить бронирование"',
    'book_down_menu': 'Для изменения бронирования на частный рейс нажмите кнопку "Изменить бронирование"',
    'reise_menu_one': 'Заявка на частный рейс\n-----------------\nСамолёт: <b>{plane}</b>\nКоличество мест: <b>{seats}</b>\nДата заявки: <b>{ask_day}</b>\nСтатус: <b>{ask_status}</b>',
    'book_menu_text': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane}</b>\nКоличество мест: <b>{seats}</b>\nЖелаемая дата вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто назначения: <b>{direction}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>',
    'book_menu_text_booking_true': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane}</b>\nАвиакомпания: <b>{company}</b>\nКоличество мест: <b>{seats}</b>\nДата и время вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто назначения: <b>{direction}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>',
    'book_menu_view_text': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane}</b>\nКоличество мест: <b>{seats}</b>\nДата заявки: <b>{ask_day}</b>\nДата и время вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто назначения: <b>{direction}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>\n-----------------\nВыберите пункт меню',
    'rew_book_menu_view_text': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane}</b>\nКоличество мест: <b>{seats}</b>\nДата заявки: <b>{ask_day}</b>\nДата и время вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто назначения: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>\n-----------------\nВыберите пункт меню',
    'no_book_to_reise': 'У вас нет бронирований на частные рейсы\nДля создания нажмите кнопку "Новое бронирование"',
    'booking': 'Ожидает подтверждения оператора',
    'ask': 'ждёт подтверждения',
    'send_phone': 'Отправить телефон',
    'user_whant_to_send_phone': 'Нажмите кнопку отправить телефон',
    'make_user_ask': 'Новое бронирование',
    'no_ask_to_reise': 'У вас нет заявок на частные рейсы\nДля создания заявки нажмите кнопку "Новое бронирование"',
    'ask_complite': 'Ваша заявка оформлена, менеджер свяжется с вами',
    'plane': 'Модель: <b>{model}</b>\nПроизводитель: <b>{prod}</b>\nКоличество мест: <b>{seats_in}</b>\nВремя лёта: <b>{flight_time}</b>',
    'plane_18': 'Модель: <b>{model}</b>\nПроизводитель: <b>{prod}</b>\nКоличество мест больше: <b>{seats_in}</b>\nВремя лёта: <b>{flight_time}</b>',
    'plane_sort_menu_text': 'Вам предоставлен список подходящих самолётов, выберите подходящий и нажмите кнопку с названием самолёта',
    'plane_info_text': 'Модель: <b>{model}</b>\nПроизводитель: <b>{prod}</b>\nКоличество мест: <b>{seats_in}</b>\nВремя лёта: <b>{flight_time}</b>\n-----------------\n\n<a href="{url}">Ссылка на сайт</a>',
    'plane_18_info_text': 'Модель: <b>{model}</b>\nПроизводитель: <b>{prod}</b>\nКоличество мест больше: <b>{seats_in}</b>\nВремя лёта: <b>{flight_time}</b>\n-----------------\n\n<a href="{url}">Ссылка на сайт</a>',
    'make_ask': 'Оформить заявку',
    'make_ask_text': 'Вы выбрали самолёт модель: <b>{model}</b>\nТребуемое количество мест: <b>{seats}</b>\nВремя лёта: <b>{flight_time}</b>\n-----------------\nВаш контактный номер телефона: <b>{phone}</b>',
    'make_ask_text_no_phone': 'Вы выбрали самолёт модель: <b>{model}</b>\nТребуемое количество мест: <b>{seats}</b>\nВремя лёта: <b>{flight_time}</b>\n-----------------\nНажмите кнопку "Отправить телефон", чтобы сформировать заявку',
    'ask_seats_message': 'Отправьте сообщение с требуемым количеством мест в самолете',
    'seats_error_message': 'Вы ввели неправильный параметр, нужно отправлять только цифры',
    'seats_message': 'Количество мест: {seats}\nВыберите желаемое время перелета',
    'planes_cat_btn': 'Каталог самолетов',
    'make_fio_message': 'Отправьте сообщение с вашим ФИО',
    'make_phone_message': 'Отправьте сообщение с вашим контактным номером телефона',
    'register_complite': 'Регистрация успешно завершена',
    'settings': 'Настройки',
    'mng_settings_text': 'Для изменения языка нажмите кнопку ru / en\nTo change the language, click ru / en',
    'settings_text': '<b>Настройки</b>\n-----------------\nТелефон: <b>{phone}</b>\nДля изменения языка нажмите кнопку ru / en\nTo change the language, click ru / en',
    'edit_fio_btn': 'Изменить ФИО',
    'edit_phone_btn': 'Изменить телефон',
    'admin_menu_text': 'Общая статистика на <b>{date}</b>\n-----------------\nЗаявки выполнено: <b>{asks_done}</b>\nБронирования выполнено: <b>{booking_done}</b>\nКоличество пользователей: <b>{users_count}</b>',
    'am_btn_stat_day': 'За сегодня',
    'am_btn_stat_week': 'За неделю',
    'am_btn_stat_month': 'За месяц',
    'manager_menu_text': 'Состояние на: {date}\n-----------------\nЗаявки: {asks_count}\nБронирования: {booking_count}',
    'mng_btn_boking': 'Бронирования',
    'mng_btn_asks': 'Заявки',
    'header_mng_booking_view': 'Список с необработаными бронированиями',
    'mng_booking_menu_text': '<b>Бронирования</b>\n-----------------\nНеобработанные: {booking_count}\nПодтвержденные: {true_booking_count}\nВыполненные: {done_booking_count}\nОтмененные: {cancel_booking_count}',
    'rew_mng_booking_details_text': 'Дата вылета: {date_pub}\nТелефон: {phone}\nЖелаемая дата вылета: {date_to_fly}\nКоличество мест: {seats}\nМесто вылета: {direction_out}\nМесто назначения: {direction}\nМесто возвращения: <b>{rew_dir}</b>\nКомментарий: {comment}',
    'mng_booking_details_text': 'Дата вылета: {date_pub}\nТелефон: {phone}\nЖелаемая дата вылета: {date_to_fly}\nКоличество мест: {seats}\nМесто вылета: {direction_out}\nМесто назначения: {direction}\nКомментарий: {comment}',
    'rew_mng_booking_details_text': 'Дата вылета: {date_pub}\nТелефон: {phone}\nЖелаемая дата вылета: {date_to_fly}\nКоличество мест: {seats}\nМесто вылета: {direction_out}\nМесто назначения: {direction}\nМесто возвращения: <b>{rew_dir}</b>\nКомментарий: {comment}',
    'mess_date_sync_done': '-----------------\n<b>Дата вылета синхронизирована</b>',
    'mess_date_sync_false': '-----------------\n<b>ВНИМАНИЕ НЕОБХОДИМО СИНХРОНИЗИРОВАТЬ ДАТУ ВЫЛЕТА В БАЗЕ ДАННЫХ</b>',
    'mng_book_sync_date_btn': 'Синхронизировать дату вылета',
    'mng_book_true_btn': 'Подтвержденные',
    'mng_book_done_btn': 'Выполненные',
    'mng_book_cancel_btn': 'Отмененные',
    'mng_reload_info_btn': 'Обновить информацию',
    'mng_make_success_btn': 'Подтвердить',
    'mng_cancel_btn': 'Отменить',
    'error': 'Ошибка',
    'mng_actual_date_year': 'Для создания автоматических напоминаний, пожалуйста отправьте сообщение в формате <b>день месяц год</b>\nНапример: <b>19 05 2019</b>',
    'mng_actual_date_done': 'Дата вылета внесена в базу данных, теперь для данного бронирования доступны автоматические напоминания.',
    'mng_actual_date_false': 'При внесении в базу данных даты вылета произошла ошибка, дату надо отправлять в формате <b>день месяц год</b>\nНапример: <b>19 05 2019</b>',
    'mng_resend': 'Повторить',
    'mng_send_new_booking': 'Создано новое бронирование\nДата создания: {date_pub}\nТелефон: {phone}\nЖелаемая дата вылета: {date_to_fly}\nКоличество мест: {seats}\nМесто вылета: {direction_out}\nМесто назначения: {direction}\nВнимание, необходимо внести дату вылета в базу данных для создания автоматических напоминаний.',
    'rew_mng_send_new_booking': 'Создано новое бронирование\nДата создания: {date_pub}\nТелефон: {phone}\nЖелаемая дата вылета: {date_to_fly}\nКоличество мест: {seats}\nМесто вылета: {direction_out}\nМесто назначения: {direction}\nМесто возвращения: <b>{rew_dir}</b>\nВнимание, необходимо внести дату вылета в базу данных для создания автоматических напоминаний.',
    'mng_update_book_info': '<b>Обновление информации</b>\n-----------------\nОтправьте сообщение с датой и временем вылета в формате <b>день.месяц.год час:минута</b>\nНапример: <b>19.05.2019 15:00</b>',
    'mng_update_book_info_date_success': '<b>Дата вылета успешно обновлена</b>\n-----------------\nОтправьте сообщение с местом вылета',
    'mng_update_book_info_date_error': 'Произошла ошибка при обновлении даты и времени вылета',
    'mng_update_book_info_direction_out': '<b>Место вылета успешно обновлено</b>\n-----------------\nОтправьте сообщение с местом прибытия',
    'mng_update_book_set_plane': '<b>Место прибытия успешно обновлено</b>\n-----------------\nОтправьте сообщение с моделью самолета',
    'mng_update_book_set_company': '<b>Модель самолета успешно установлена</b>\n-----------------\nОтправьте сообщение с названием авиакомпании',
    'mng_update_book_set_price': '<b>Авиакомпания успешно установлена</b>\n-----------------\nОтправьте сообщение со стоимостью перелета',
    'mng_update_book_done': '<b>Стоимость перелета успешно установлена</b>\n-----------------\nНовые данные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМодель самолета: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>',
    'mng_book_set_true': 'Бронь подтвержденна, пользователь оповещён',
    'mng_book_set_cancel': 'Бронь отменена, пользователь оповещён',
    'user_booking_true_text': '<b>Бронирование подтвержденно</b>\n-----------------\nДанные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМодель самолета: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>',
    'rew_user_booking_true_text': '<b>Бронирование подтвержденно</b>\n-----------------\nДанные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nМодель самолета: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>',
    'user_booking_cancel_text': '<b>Бронирование отменено</b>\n-----------------\nДанные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМодель самолета: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>',
    'rew_user_booking_cancel_text': '<b>Бронирование отменено</b>\n-----------------\nДанные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nМодель самолета: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>',
    'view_booking_by_user_text': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>\nКоличество мест: <b>{seats}</b>\nДата и время вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>',
    'rew_view_booking_by_user_text': 'Бронирование на частный рейс\n-----------------\nСамолёт: <b>{plane_model}</b>\nАвиакомпания: <b>{company}</b>\nСтоимость перелета: <b>{price}</b>\nКоличество мест: <b>{seats}</b>\nДата и время вылета: <b>{date}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>\nМесто возвращения: <b>{rew_dir}</b>\nКоментарий: <b>{comment}</b>\nСтатус: <b>{ask_status}</b>',
    'true_booking': 'Бронирование подтвержденно',
    'mng_header_true_booking_menu': 'Список с подтвержденными бронированиями',
    'mng_booking_true_short_text': 'Данные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>',
    'mng_booking_true_no_booking': 'Подтвержденных бронирований нет',
    'mng_booking_true_footer_text': '<b>Подтвержденные бронирования</b>\n-----------------\nОбщее количество: {true_booking_count}',
    'mng_header_done_booking_menu': 'Список с выполненными бронированиями',
    'mng_booking_done_short_text': 'Данные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>',
    'mng_booking_done_no_booking': 'Выполненных бронирований нет',
    'mng_booking_done_footer_text': '<b>Выполненные бронирования</b>\n-----------------\nОбщее количество: {true_booking_count}',
    'mng_header_cancel_booking_menu': 'Список с отмененными бронированиями',
    'mng_booking_cancel_short_text': 'Данные по бронированию:\nДата и время вылета: <b>{date_fly}</b>\nМесто вылета: <b>{direction_out}</b>\nМесто прибытия: <b>{direction}</b>',
    'mng_booking_cancel_no_booking': 'Отмененных бронирований нет',
    'mng_booking_cancel_footer_text': '<b>Отмененные бронирования</b>\n-----------------\nОбщее количество: {true_booking_count}',
    'header_mng_asks_view': 'Список с необработаными заявками',
    'mng_asks_menu_text': '<b>Заявки</b>\n-----------------\nНеобработанные: {asks_count}\nВыполненные: {done_asks_count}',
    'mng_ask_short_text': 'Самолёт: <b>{plane}</b>\nЖелаемое количество мест: <b>{seats}</b>\nТелефон: <b>{phone}</b>',
    'mng_ask_no_asks_text': 'Нет необработанных заявок',
    'mng_ask_set_true': 'Выполнить',
    'mng_ask_set_true_succes': 'Заявке присвоен статус: выполнено, пользователь оповещён',
    'mng_ask_details_text': 'Дата создания заявки: <b>{date}</b>\nИнформация о самолёте:\n{plane}\n-----------------\nИнформация о пользователе:\nТелефон: <b>{phone}</b>\nЖелаемое количество мест: <b>{seats}</b>',
    'user_ask_details_text': 'Вашей заявке присвоен статус: <b>ВЫПОЛНЕНО</b>\nДата создания заявки: <b>{date}</b>\nИнформация о самолёте:\n{plane}\n-----------------\nИнформация о пользователе:\nТелефон: <b>{phone}</b>\nЖелаемое количество мест: <b>{seats}</b>',
    'mng_header_done_asks_menu': 'Список с выполненными заявками',
    'mng_ask_done_short_text': 'Данные по заявке:\nСамолёт: <b>{plane}</b>\nЖелаемое количество мест: <b>{seats}</b>\nТелефон: <b>{phone}</b>',
    'mng_ask_done_no_ask': 'Выполненных заявок нет',
    'mng_ask_done_footer_text': '<b>Выполненные заявки</b>\n-----------------\nОбщее количество: {done_ask_count}',
    'mng_ask_details_text_created': '<b>Создана новая заявка</b>\n-----------------\nДата создания заявки: <b>{date}</b>\nИнформация о самолёте:\n{plane}\n-----------------\nИнформация о пользователе:\nТелефон: <b>{phone}</b>\nЖелаемое количество мест: <b>{seats}</b>',
}

en = {
    'ru_lang': 'Русский',
    'en_lang': 'English',
    'choose_lang_text': 'Выберите язык / Choose language',
    'mng_settings_text': 'Для изменения языка нажмите кнопку ru / en\nTo change the language, click ru / en',
    'hard_reise_alert_text': '<b>Multiple destinations created</b>\n-----------------\nDate creation: <b>{date}</b>\nPhone: <b>{phone}</b>\nComment:\n{comment}',
    'hard_reise_btn': 'Multiple destinations #{booking_id}',
    'hard_reise_view': 'Multiple destinations #{booking_id}\n-----------------\nDate creation: <b>{date}</b>\nPhone: <b>{phone}</b>\nComment:\n{comment}',
    'hard_reise_cancel_view': '<b>Booking canceled</b>\nMultiple destinations # {booking_id}\n-----------------\nCreation Date: <b>{date}</b>\nPhone: <b>{phone}</b>\nComment:\n{comment}',
    'hard_reise_true_view': '<b>Booking confirmed</b>\nMultiple destinations # {booking_id}\n-----------------\nCreation Date: <b>{date}</b>\nPhone: <b>{phone}</b>\nComment:\n{comment}',
    'user_id_btn': 'ID: {user}',
    'book_btn': '{dir_out} / {dir_in}',
    'rew_book_btn': '{dir_out} / {dir_in} / {dir_out}',
    'develop_message': 'This section is under development',
    'book_one_direction_btn': 'One way flight',
    'book_two_direction_btn': 'Round trip',
    'book_hard_direction_btn': 'Multiple destinations',
    'make_hard_reise_text': 'Please send a message with scheduled flight',
    'hard_reise_meked_text': 'The request for a multiple destination flight is received, our sales team will revert with confirmation',
    'makebook_choise_menu': 'Charter flight booking\n-----------------\nChoose charter flight option',
    'lang_change_btn': 'ru / en',
    'alert_text': 'Reminder for charter flight reservation: \nDeparture: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nArrival: <b>{direction}</b>\nNumber of passengers: <b>{seats}</b>',
    'rew_alert_text': 'Reminder about booking a Charter flight\nDate of departure: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nArrival: <b>{direction}</b>\nPlace of return: <b>{rew_dir}</b>\nNumber of passengers: <b>{seats}</b>',
    'day': 'per day',
    'week': 'per week',
    'month': 'per month',
    'admin_stata_menu_text': 'Statistics <b>{period}</b>\n-----------------\nNew bookings: <b>{new_booking}</b>\nBookings confirmed: <b>{true_booking}</b>\nBookings complited: <b>{done_booking}</b>\nBookings cancelled: <b>{cancel_booking}</b>\nNew requests: <b>{new_ask}</b>\nConfirmed requests:: <b>{done_ask}</b>',
    'not_set': 'not set',
    'cancel_booking': 'Cancel booking',
    'edited': 'Edited',
    'edit_date_fly_btn': 'Change departure date',
    'edit_date_fly_text': 'Send a message with a new departure date',
    'edit_direction_out_btn': 'Change departure airport',
    'edit_direction_out_text': 'Send a message with your new departure airport',
    'edit_direction_btn': 'Change destination airport',
    'edit_direction_text': 'Send a message with the new destination airpot',
    'edit_seats_btn': 'Change the number of passengers',
    'edit_seats_text': 'Send a message with a new number of passengers',
    'edit_comment_btn': 'Add comment',
    'edit_comment_text': 'Send a message with your comments re your reservation',
    'from_place_text': 'Send a message with the departure airport',
    'two_from_place_text': 'Send a message with the Departure place and return',
    'to_direction_place_text': 'Send a message with the place of arrival',
    'date_fly_text': 'Send a message with the date of departure',
    'booking_message_text': 'Reservations created\nDesired departure date: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>\nNumber of passengers: <b>{seats}</b>\n-----------------\nThe reservation is created, the operator will contact you within an hour',
    'rew_booking_message_text': 'Reservations created\nDesired departure date: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>\nPlace of return: <b>{rew_dir}</b>\nNumber of passengers: <b>{seats}</b>\n-----------------\nThe reservation is created, the operator will contact you within an hour',
    'booking_message_text_seats_error': 'Reservations created\nDesired departure date: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>\nSince the bot could not recognize the number of passengers, was automatically set: <b>{seats}</b>\n-----------------\nThe reservation is created, the operator will contact you within an hour',
    'fl_time_1-2': 'Up to 6 hours',
    'fl_time_3-5': '6 to 9 hours',
    'fl_time_5-10': 'Over 9 hours',
    'error_message': 'An error occurred',
    'reload_btn': 'Refresh',
    'view': 'Read more',
    'superadmin_menu_text': 'Welcome superadmin',
    'su_admins_btn': 'Admin Management',
    'hiadmin': 'Hi admin {name}',
    'hello_message_reg_user': 'You can book a charter flight or check the aircraft catalogue',
    'hello_message': 'Welcome to Global Jet! <b>{username}</b>\nYou can book a charter flight or view the aircraft catalogue, please proceed to registration.',
    'next': 'Next',
    'back': 'Back',
    'plane_no_append': 'No aircraft assigned',
    'register': 'Sigin',
    'edit_booking': 'Change booking',
    'yes_make_ask': 'Confirm booking',
    'back_to_menu_btn': 'Back to menu',
    'reise': 'Charter flight',
    'reise_down_menu': 'You can find your bookings, to change your reservation please press a button "Change booking"',
    'book_down_menu': 'To change your booking for a Charter flight, click the `Change booking` button.',
    'reise_menu_one': 'Charter flight request\n-----------------\nAircraft: <b>{plane}</b>\nNumber of seats: <b>{seats}</b>\nrequest date: <b>{ask_day}</b>\nStatus: <b>{ack_status}</b>',
    'book_menu_text': 'Charter flight booking\n-----------------\nAircraft: <b>{plane}</b>\nNumber of seats: <b>{seats}</b>\nDesired departure date: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nDestination: <b>{direction}</b>\nComment: <b>{comment}</b>\nStatus: <b>{ask_status}</b>',
    'book_menu_text_booking_true': 'Charter flight booking\n-----------------\nAircraft: <b>{plane}</b>\nAirline: <b>{company}</b>\nNumber of seats: <b>{seats}</b>\ndate and time of departure: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nDestination: <b>{direction}</b>\nComment: <b>{comment}</b>\nStatus: <b>{ask_status}</b>',
    'book_menu_view_text': 'Charter flight booking\n-----------------\nAircraft: <b>{plane}</b>\nNumber of seats: <b>{seats}</b>\nrequest date: <b>{ask_day}</b>\ndate and time of departure: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nDestination: <b>{direction}</b>\nComment: <b>{comment}</b>\nStatus: <b>{ask_status}</b>\n-----------------\nSelect menu item',
    'rew_book_menu_view_text': 'Charter flight booking\n-----------------\nAircraft: <b>{plane}</b>\nNumber of seats: <b>{seats}</b>\nrequest date: <b>{ask_day}</b>\ndate and time of departure: <b>{date}</b>\nDeparture place: <b>{direction_out}</b>\nDestination: <b>{direction}</b>\nReturn: <b>{rew_dir}</b>\nComment: <b>{comment}</b>\nStatus: <b>{ask_status}</b>\n-----------------\nSelect menu item',
    'no_book_to_reise': 'You do not have Charter flight booking\nTo create, click on the `New Booking` button',
    'booking': 'Waiting for operator confirmation',
    'ask': 'waiting for confirmation',
    'send_phone': 'Send phone',
    'user_whant_to_send_phone': 'Click send phone',
    'make_user_ask': 'New Booking',
    'no_ask_to_reise': 'You have no requests for Charter flights\nTo create an request, click on the `New Booking` button',
    'ask_complite': 'Your request is filed, the manager will contact you',
    'plane': 'Model: <b>{model}</b>\nManufacturer: <b>{prod} </b>\nNumber of seats: <b>{seats_in}</b>\nTime: <b>{flight_time}</b>',
    'plane_18': 'Model: <b>{model}</b>\nManufacturer: <b>{prod}</b>\nNumber of seats more: <b>{seats_in}</b>\nTime: <b>{flight_time}</b> ',
    'plane_sort_menu_text': 'You are given a list of suitable aircraft, select the appropriate one and press the button with the name of the aircraft',
    'plane_info_text': 'Model: <b>{model}</b>\nManufacturer: <b>{prod}</b>\nNumber of seats: <b>{seats_in}</b>\nTime: <b>{flight_time}</b>\n-----------------\n\n<a href="{url}">Link to the site</a>',
    'plane_18_info_text': 'Model: <b>{model}</b>\nManufacturer: <b>{prod}</b>\nNumber of seats more: <b>{seats_in}</b>\nTime: <b>{flight_time}</b>\n-----------------\n\n<a href="{url}">Link to site</a>',
    'make_ask': 'Make a request',
    'make_ask_text': 'You have chosen a model airplane: <b>{model}</b>\nRequired seating: <b>{seats}</b>\nTime: <b>{flight_time}</b>\n--- --------------\nYour contact phone number: <b>{phone}</b> ',
    'make_ask_text_no_phone': 'You have chosen a model airplane: <b>{model}</b>\nRequired seating: <b>{seats}</b>\nTime: <b>{flight_time}</b>\n--- --------------\nClick `Send Phone` button to form an request ',
    'ask_seats_message': 'Send a message with the required number of seats in the plane',
    'seats_error_message': 'You have entered an incorrect parameter, you need to send only numbers',
    'seats_message': 'Number of seats: {seats}\nSelect the desired flight time',
    'planes_cat_btn': 'Aircraft Catalog',
    'make_fio_message': 'Send a message with your full name',
    'make_phone_message': 'Send a message with your contact phone number',
    'register_complite': 'Registration successfully completed',
    'settings': 'Settings',
    'settings_text': '<b>Settings</b>\n-----------------\nPhone: <b>{phone}</b>\nДля изменения языка нажмите кнопку 🇷🇺 / 🇬🇧\nTo change the language, click 🇷🇺 / 🇬🇧',
    'edit_fio_btn': 'Change Name',
    'edit_phone_btn': 'Change phone',
    'admin_menu_text': 'General statistics on <b>{date}</b>\n-----------------\nrequest has been completed: <b>{asks_done}</b>\nBooking has been completed : <b>{booking_done}</b>\nNumber of users: <b>{users_count}</b> ',
    'am_btn_stat_day': 'Today',
    'am_btn_stat_week': 'Week',
    'am_btn_stat_month': 'Month',
    'manager_menu_text': 'Status on: {date}\n-----------------\nrequests: {asks_count}\nBooking: {booking_count}',
    'mng_btn_boking': 'Bookings',
    'mng_btn_asks': 'request',
    'header_mng_booking_view': 'List with raw Bookings',
    'mng_booking_menu_text': '<b>Bookings</b>\n-----------------\nUntreated: {booking_count}\nConfirmed: {true_booking_count}\nCompleted: {done_booking_count}\nCancelled: {cancel_booking_count} ',
    'rew_mng_booking_details_text': 'Departure date: {date_pub}\nPhone: {phone}\nDelable departure date: {date_to_fly}\nNumber of seats: {seats}\nDestroom: {direction_out}\nDestination Location: {direction}\nRest Location: <b>{rew_dir}</b>\nComment: {comment} ',
    'mng_booking_details_text': 'Departure date: {date_pub}\nPhone: {phone}\nRelated departure date: {date_to_fly}\nNumber of seats: {seats}\nDestroom: {direction_out}\nDestination location: {direction}\nComment: {comment}',
    'rew_mng_booking_details_text': 'Departure date: {date_pub}\nPhone: {phone}\nDelable departure date: {date_to_fly}\nNumber of seats: {seats}\nDestroom: {direction_out}\nDestination Location: {direction}\nRest Location: <b>{rew_dir}</b>\nComment: {comment} ',
    'mess_date_sync_done': '-----------------\n<b>Departure date synchronized</b>',
    'mess_date_sync_false': '-----------------\n<b>ATTENTION IT IS NECESSARY TO SYNCHRONIZE THE DATE OF DEPARTURE IN THE DATABASE</b>',
    'mng_book_sync_date_btn': 'Sync departure date',
    'mng_book_true_btn': 'Confirmed',
    'mng_book_done_btn': 'Completed',
    'mng_book_cancel_btn': 'Canceled',
    'mng_reload_info_btn': 'Update info',
    'mng_make_success_btn': 'Confirm',
    'mng_cancel_btn': 'Cancel',
    'error': 'Error',
    'mng_actual_date_year': 'To create automatic reminders, please send a message in the format <b>day month year</b>\nFor example: <b>19 05 2019</b>',
    'mng_actual_date_done': "The departure date is entered in the database, now automatic reminders are available for this booking.",
    'mng_actual_date_false': 'An error occurred when adding the date of departure to the database; the date should be sent in the format <b>day month year</b>\nFor example: <b>19 05 2019</b>',
    'mng_resend': 'Repeat',
    'mng_send_new_booking': 'Created a new Booking\nDate of creation: {date_pub}\nPhone: {phone}\nDelable date of departure: {date_to_fly}\nNumber of seats: {seats}\nDest: {direction_out}\nA destination: {direction}\nAttention, necessary Enter the departure date in the database to create automatic reminders.',
    'rew_mng_send_new_booking': 'Created a new Booking\nDate of creation: {date_pub}\nPhone: {phone}\nDelable date of departure: {date_to_fly}\nNumber of seats: {seats}\nDest point: {direction_out}\nPlace of destination: {direction}\nPlace return: <b>{rew_dir}</b>\nAttention, you must enter the departure date in the database to create automatic reminders.',
    'mng_update_book_info': '<b>Update</b>\n-----------------\nSend a message with the date and time of departure in the format of <b>day.month year year hour: minute</b>\nFor example: <b>05/19/2019 15:00</b> ',
    'mng_update_book_info_date_success': '<b>Departure date successfully updated</b>\n-----------------\nSend a message with the Departure place',
    'mng_update_book_info_date_error': 'An error occurred while updating the departure date and time',
    'mng_update_book_info_direction_out': '<b>Departure place successfully updated</b>\n-----------------\nSend a message with the place of arrival',
    'mng_update_book_set_plane': '<b>Place of arrival successfully updated</b>\n-----------------\nSend a message with the aircraft model',
    'mng_update_book_set_company': '<b>Aircraft model successfully installed</b>\n-----------------\nSend a message with the airline name',
    'mng_update_book_set_price': '<b>Airline successfully installed</b>\n-----------------\nSend a message with the cost of the flight',
    'mng_update_book_done': '<b>Flight cost has been successfully established</b>\n-----------------\nNew booking details:\nDate and departure time: <b>{date_fly} < / b>\nDest: <b>{direction_out}</b>\nDesign: <b>{direction}</b>\nAircraft model: <b>{plane_model}</b>\nAirline: <b > {company}</b>\nFreight Cost: <b>{price}</b> ',
    'mng_book_set_true': 'Booking confirmed, user notified',
    'mng_book_set_cancel': 'Booking canceled, user notified',
    'user_booking_true_text': '<b>Booking confirmed</b>\n-----------------\nBooking data:\nDate and departure time: <b>{date_fly}</b>\nDest: <b>{direction_out}</b>\nPlace of arrival: <b>{direction}</b>\nAircraft model: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nThe cost of the flight: <b>{price}</b> ',
    'rew_user_booking_true_text': '<b>Booking confirmed</b>\n-----------------\nBooking data:\nDate and departure time: <b>{date_fly}</b>\nDest: <b>{direction_out}</b>\nPlace of arrival: <b>{direction}</b>\nPlace of return: <b>{rew_dir}</b>\nAircraft model: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nFare: <b>{price}</b> ',
    'user_booking_cancel_text': '<b>Booking canceled</b>\n-----------------\nBooking data:\nDate and departure time: <b>{date_fly}</b>\nDest: <b>{direction_out}</b>\nPlace of arrival: <b>{direction}</b>\nAircraft model: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nThe cost of the flight: <b>{price}</b> ',
    'rew_user_booking_cancel_text': '<b>Booking canceled</b>\n-----------------\nBooking data:\nDate and departure time: <b>{date_fly}</b>\nDest: <b>{direction_out}</b>\nPlace of arrival: <b>{direction}</b>\nPlace of return: <b>{rew_dir}</b>\nAircraft model: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nFare: <b>{price}</b> ',
    'view_booking_by_user_text': 'Booking for a Charter flight\n-----------------\nAircraft: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nThe cost of the flight: <b>{price}</b>\nNumber of seats: <b>{seats}</b>\nDate and time of departure: <b>{date}</b>\nDesign: <b > {direction_out}</b>\nPlace of arrival: <b>{direction}</b>\nCommentary: <b>{comment}</b>\nStatus: <b>{ask_status}</b> ',
    'rew_view_booking_by_user_text': 'Booking for a Charter flight\n-----------------\nAircraft: <b>{plane_model}</b>\nAirline: <b>{company}</b>\nThe cost of the flight: <b>{price}</b>\nNumber of seats: <b>{seats}</b>\nDate and time of departure: <b>{date}</b>\nDesign: <b > {direction_out}</b>\nArrival Location: <b>{direction}</b>\nReturn Location: <b>{rew_dir}</b>\nComment: <b>{comment}</b>\nStatus: <b>{ask_status}</b> ',
    'true_booking': 'Booking confirmed',
    'mng_header_true_booking_menu': 'List with confirmed Bookings',
    'mng_booking_true_short_text': 'Booking information:\nDate and departure time: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>',
    'mng_booking_true_no_booking': 'No confirmed bookings',
    'mng_booking_true_footer_text': '<b>Confirmed Bookings</b>\n-----------------\nTotal: {true_booking_count}',
    'mng_header_done_booking_menu': 'List with booked Bookings',
    'mng_booking_done_short_text': 'Booking information:\nDate and departure time: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>',
    'mng_booking_done_no_booking': 'No bookings completed',
    'mng_booking_done_footer_text': '<b>Bookings Made</b>\n-----------------\nTotal: {true_booking_count}',
    'mng_header_cancel_booking_menu': 'List with canceled Bookings',
    'mng_booking_cancel_short_text': 'Booking information:\nDate and departure time: <b>{date_fly}</b>\nDeparture place: <b>{direction_out}</b>\nArrival place: <b>{direction}</b>',
    'mng_booking_cancel_no_booking': 'No canceled bookings',
    'mng_booking_cancel_footer_text': '<b>Canceled Bookings</b>\n-----------------\nTotal: {true_booking_count}',
    'header_mng_asks_view': 'List of unprocessed requests',
    'mng_asks_menu_text': '<b>Request</b>\n-----------------\nUntreated: {asks_count}\nPervised: {done_asks_count}',
    'mng_ask_short_text': 'Airplane: <b>{plane}</b>\nProvided seating capacity: <b>{seats}</b>\nPhone: <b>{phone}</b>',
    'mng_ask_no_asks_text': 'No unprocessed requests',
    'mng_ask_set_true': 'Confirm',
    'mng_ask_set_true_succes': 'Request assigned status: done, user notified',
    'mng_ask_details_text': 'request Creation Date: <b>{date}</b>\nAircraft Information:\n{plane}\n-----------------\nUser Information:\nPhone: <b>{phone}</b>\nDesired Seats: <b>{seats}</b> ',
    'user_ask_details_text': 'Your request has been assigned the status: <b>COMPLETED</b>\nThe creation date of the request: <b>{date}</b>\nInformation about the aircraft:\n{plane}\n--------- --------\nUser Information:\nPhone: <b>{phone}</b>\nProvided Seats: <b>{seats}</b> ',
    'mng_header_done_asks_menu': 'List with completed requests',
    'mng_ask_done_short_text': 'Request details:\nAircraft: <b>{plane}</b>\nProvided number of seats: <b>{seats}</b>\nPhone: <b>{phone}</b>',
    'mng_ask_done_no_ask': "There are no completed requests",
    'mng_ask_done_footer_text': '<b>Completed requests</b>\n-----------------\nThe total number: {done_ask_count}',
    'mng_ask_details_text_created': '<b>New request created</b>\n-----------------\nDate creation date: <b>{date}</b>\nAirline information:\n{plane}\n-----------------\nUser Information:\nPhone: <b>{phone}</b>\nProvided Number of Seats: <b>{seats}</b> ',
}
