# -*- coding: utf-8 -*-

ru = {
    ############ Кнопки
    'settings': 'Lang / Язык',
    'to_menu_btn': 'В меню',
    'next': 'Вперед',
    'back_p': 'Назад',
    'cancel_mnu_btn': 'Отменить',
    'end_mnu_btn': 'Завершить',
    'edit_name': 'Изменить название',
    'edit_date': 'Изменить дату или время',
    'edit_theme': 'Изменить повестку',
    'edit_users': 'Изменить участников',
    'letsgo_btn': 'Приступить',
    'yes': 'Да',
    'no': 'Нет',
    'learn_mnu_btn': 'Обучение',
    'test_mnu_btn': 'Тестирование',
    'tasks_mnu_btn': 'Задачи',
    'add_task_to_user': 'Поставить задачу',
    'user_creator_task_btn': 'Задачи созданные вами',
    'im_do_this_task': 'Принять к исполнению',
    'fuck_this_task': 'Отклонить',
    'close_task_mnu_btn': 'Выполнить',
    'end_tasks_mnu_btn': 'Выполненные задачи',
    'polls_mnu_btn': 'Опросы',
    'add_poll_mnu_btn': 'Создать опрос',
    'arch_polls': 'Архив опросов',
    'end_poll': 'Завершить',
    'meet_mnu_btn': 'Собрания',
    'create_group_mnu_btn': 'Создать аккаунт',
    'get_learn_mnu_btn': 'Пройти обучение',
    're_learn_btn': 'Повторить обучение',
    'users_mnu_btn': 'Пользователи',
    'groups_view_btn': 'Аккаунты',
    'user_group_mnu_btn': 'Аккаунт',
    'group_owner_view_btn': 'Аккаунт организации',
    'add_user_to_refer': 'Пригласить пользователя',
    'test_question': 'Проверочный вопрос',
    'cheked': '✅',
    'nocheked': ' ',
    'answer_btn': '{number} {chk}',
    'test_chek_answer_btn': 'Проверить ответ',
    'next_learn_question_btn': 'Следующий вопрос',
    'end_learn_question_btn': 'Закончить обучение',
    'learn_curs_btn': '{curs_name}',
    'create_forum_mnu_btn': 'Запланировать собрание',
    'end_forum_mnu_btn': 'Завершенные собрания',
    'now_date': 'Сегодня',
    'tomorrow_date': 'Завтра',
    'to_week_day': 'Через неделю',
    'add_date': 'Ввести вручную',
    'create_forum_end_btn': 'Запланировать собрание',
    'edit_forum_users_end': 'Закончить редактирование',
    'aprowe_btn': 'Подтвердить',
    'cancel_reg': 'Отклонить',
    'view_task': 'Посмотреть задачу',
    'add_forum_comment': 'Подвести итоги собрания',
    'relearn_btn': 'Повторить обучение',
    'create_acc': 'Создать аккаунт',
    'en_lng_btn': 'English',
    'ru_lng_btn': 'Русский',
    'settings_menu_text': 'Выберите язык / Choose language',

    ############
    'acc_not_created': 'Аккаунт не создан',
    'bad_test_text': '\n---------------------\nТест не пройден, рекомендуем пройти обучение еще раз',
    'forum_ended_head': 'Собрание закончено\n',
    'forum_details_text_alert_15_min': '<b>Через 15 минут начнется собрание:\n{forum_name}</b>\n---------------------\nСоздатель собрания: <b>{username}</b>\nДата создания: <b>{date_create}</b>\nДата и время начала: <b>{date_start}</b>\nПродолжительность собрания: <b>{time_delta}</b>\n---------------------\n{forum_theme}\n---------------------\n{users}',
    'alert_15_do_task': 'Подходит время завершения задачи <b>{task_name}</b>\n---------------------\nСоздатель задачи: <b>{creator_username}</b>\nДата создания: <b>{date_start}</b>\nДата завершения: <b>{date_end}</b>\nОписание задачи:\n\n{task_text}',
    'alert_cancel_task': 'Задача <b>{task_name}</b> отклонена',
    'alert_do_task': 'Задача <b>{task_name}</b> принята к исполнению',
    'alert_close_task': 'Задача <b>{task_name}</b> завершена\nКомментарий:\n{comment}',
    'refer_aprowed_user_text': 'Регистрация пользователя успешно подтверждена',
    'refer_cancel_user_text': 'Регистрация пользователя отклонена',
    'message_send_cancel_user_text': '<b>{refer_username}</b> отклонил вашу кандидатуру в компании <b>{group_name}</b>.\nПожалуйста создайте свой аккаунт и пригласите туда пользователей, для этого нажмите кнопку "Аккаунт"',
    'message_send_aprowed_user_text': '<b>{refer_username}</b> подтвердил регистрацию в компании <b>{group_name}</b>.\nВы можете ставить задачи друг другу, назначать встречи или проводить опросы.',
    'message_send_new_referal': 'Зарегистрирован новый пользователь в аккаунте <b>{group_name}</b>\nИмя: <b>{username}</b>\nДата регистрации: <b>{date_reg}</b>\n---------------------\nПодтвердите или отклоните регистрацию пользователя',
    'end_test_and_results_text': '<b>Тестирование закончено</b>\n{results}',
    'forum_update_theme_text': 'Отправьте сообщение с темой собрания или перечень вопросов для обсуждения',
    'forum_update_name_text': 'Отправьте сообщение с новым названием собрания',
    'forum_end_add_comment_text': 'Отправьте текстовый комментарий с итогами собрания',
    'poll_create_manual_time_again_menu': '<b>Время завершения опроса</b>\nПроизошла ошибка при добавлении времени завершения опроса, попробуйте еще раз\nОтправьте сообщение с временем завершения опроса\nНапример: <b>14:35</b>',
    'poll_create_manual_time_menu': '<b>Время завершения опроса</b>\nОтправьте сообщение с временем завершения опроса\nНапример: <b>14:35</b>',
    'poll_create_time_text': '<b>Время завершения опроса</b>\nВыберите время завершения опроса',
    'poll_create_get_date': '<b>Дата завершения опроса</b>\nВыберите дату завершения опроса',
    'task_create_manual_time_again_menu': '<b>Время завершения задачи</b>\nПроизошла ошибка при добавлении времени завершения задачи, попробуйте еще раз\nОтправьте сообщение с временем завершения задачи\nНапример: <b>14:35</b>',
    'task_create_manual_time_menu': '<b>Время завершения задачи</b>\nОтправьте сообщение с временем завершения задачи\nНапример: <b>14:35</b>',
    'task_create_time_text': '<b>Время завершения задачи</b>\nВыберите время завершения задачи или вы можете ввести время вручную, для этого нажмите кнопку "Ввести вручную"',
    'task_create_get_date': '<b>Дата завершения задачи</b>\nВыберите дату завершения задачи',
    'forum_create_manual_time_agian_menu': '<b>{forum_name}</b>\nПроизошла ошибка добавления времени собрания, попробуйте еще раз\nОтправьте сообщение с временем начала собрания\nНапример: <b>09:35</b>',
    'forum_create_manual_time_menu': '<b>{forum_name}</b>\nОтправьте сообщение с временем начала собрания\nНапример: <b>09:35</b>',
    'forum_create_delta_time': '<b>{forum_name}</b>\nУкажите примерную продолжительность собрания',
    'forum_create_theme_text': '<b>{forum_name}</b>\nОтправьте сообщение с темой собрания или перечень вопросов для обсуждения',
    'forum_add_users': '<b>{forum_name}</b>\nВыберите пользователей для приглашения их на собрание',
    'forum_add_users_nousers': 'К сожалению нет пользователей для приглашения их на собрание',
    'forum_create_time_text': '<b>{forum_name}</b>\nВыберите время начала собрания или вы можете ввести время вручную, для этого нажмите кнопку "Ввести вручную"',
    'forum_create_date_text_again': '<b>{forum_name}</b>\nВы допустили ошибку при отправке даты, попробуйте еще раз\nОтправьте дату начала собрания, например: <b>{date_now}</b>',
    'forum_create_date_text': '<b>{forum_name}</b>\nОтправьте дату начала собрания, например: <b>{date_now}</b>',
    'forum_create_name_text': 'Отправьте сообщение с названием собрания',
    'forum_create_get_date': '<b>{forum_name}</b>\nВыберите дату собрания',
    'nogroup_user': 'Вы не создали аккаунт\nНажмите кнопку "Аккаунт" для создания аккаунта',
    'forum_details_text': '<b>{forum_name}</b>\n---------------------\nСоздатель собрания: <b>{username}</b>\nДата создания: <b>{date_create}</b>\nДата и время начала: <b>{date_start}</b>\nПродолжительность собрания: <b>{time_delta}</b>\n---------------------\n{forum_theme}\n---------------------\n{users}\n{comment}',
    'noclosed_forums_menu_text': '<b>Завершенные собрания</b>\n---------------------\nНет завершенных собраний',
    'noactive_forums_menu_text': '<b>Запланированные собрания</b>\n---------------------\nНет запланированных собраний',
    'closed_forums_menu_text': '<b>Завершенные собрания</b>\n---------------------\nКоличество: {count}',
    'active_forums_menu_text': '<b>Запланированные собрания</b>\n---------------------\nКоличество: {count}',
    'forums_menu_text': '<b>Собрания</b>\n---------------------\nСписок с запланированными собраниями',
    'noforums_menu_text': '<b>Собрания</b>\n---------------------\nК сожалению запланированных собраний нет, но вы можете создать новую',
    'task_comment': '\n---------------------\n{comment}',
    'close_task_get_comment': 'Отправьте комментарий о выполнении задачи',
    'task_end': 'Завершена',
    'task_active': 'Активна',
    'task_doing': 'Принята к исполнению',
    'task_cancel': 'Отклонена',
    'user_nodoing_task_menu_text': '<b>Принятые к исполнению задачи</b>\n---------------------\nНет задач принятых к исполнению',
    'user_nofucked_task_menu_text': '<b>Отклоненные задачи</b>\n---------------------\nНет отклоненных задач',
    'user_noactive_task_menu_text': '<b>Активные задачи</b>\n---------------------\nНет активных задач',
    'user_noclosed_task_menu_text': '<b>Выполненные задачи</b>\n---------------------\nНет выполненных задач',
    'user_doing_task_menu_text': '<b>Принятые к исполнению задачи</b>\n---------------------\nКоличество: {task_count}',
    'user_fucked_task_menu_text': '<b>Отклоненные задачи</b>\n---------------------\nКоличество: {task_count}',
    'user_active_task_menu_text': '<b>Активные задачи</b>\n---------------------\nКоличество: {task_count}',
    'user_closed_task_menu_text': '<b>Выполненные задачи</b>\n---------------------\nКоличество: {task_count}',
    'task_details_text': '<b>{task_name}</b>\n---------------------\nСоздатель задачи: <b>{creator_username}</b>\nДата создания: <b>{date_start}</b>\nДата завершения: <b>{date_end}</b>\nСтатус задачи: {status}\nОписание задачи:\n\n{task_text}{comment}',
    'create_task_date_end_text_again': 'Произошла ошибка при добавлении даты окончания задачи, попробуйте еще раз\nОтправьте сообщение с датой и временем окончания задачи\nНапример: <b>{date_end}</b>',
    'create_task_date_end_text': 'Отправьте сообщение с датой и временем окончания задачи\nНапример: <b>{date_end}</b>',
    'create_task_text_text': 'Отправьте сообщение с описанием задачи',
    'create_task_name_text': 'Отправьте сообщение с названием задачи',
    'user_select_user_to_add_task_nousers': '<b>{groupname}</b>\n---------------------\nК сожалению в вашем аккаунте нет других пользователей кроме вас\nВоспользуйтесь ссылкой для приглашения пользователей\nСкопируйте ссылку и отправьте коллегам в Телеграм, чтобы пригласить их в ваш аккаунт:\n{refer_link}',
    'user_select_user_to_add_task': '<b>{groupname}</b>\n---------------------\nОбщее количество пользователей: <b>{users_count}</b>\nДля создания задачи выберите пользователя',
    'user_task_menu_text': '<b>Задачи</b>\n---------------------\nСписок назначенных вам задач',
    'user_notask_menu_text': '<b>Задачи</b>\n---------------------\nУ вас нет назначенных вам задач',
    'user_select_poll_variant_ans_text': 'Вы вбрали\n{var}\nРезультаты опроса будут доступны при завершении опроса',
    'user_arch_polls_menu_text': '<b>Архивные опросы</b>\n---------------------\nВыберите опрос для просмотра статистики',
    'user_arch_nopolls_menu_text': '<b>Архивные опросы</b>\n---------------------\nК сожалению нет архивных опросов',
    'active': 'Опубликован',
    'passive': 'В архиве',
    'poll_results': '\nРезультат опроса:\n{poll_results}',
    'user_polled_varname': '\nВы выбрали вариант:\n{varname}',
    'create_poll_add_date_end': 'Отправьте сообщение с датой окончания опроса\nНапример: <b>{date_end}</b>',
    'create_poll_add_date_end_error': 'Произошла ошибка в добавлении даты завершения опроса\nОтправьте сообщение с датой окончания опроса\nНапример: <b>{date_end}</b>',
    'poll_detail_text': '<b>{pollname}</b>\n{polltext}\n---------------------\nДата создания: <b>{date_create}</b>\nДата завершения: <b>{date_end}</b>\nСтатус: <b>{status}</b>{results}',
    'create_poll_poll_chooses_text': 'Отправьте варианты ответа на опрос, начиная каждый вариант с <b>/</b>\nНапример: /Да /Нет',
    'create_poll_polltext_text': 'Отправьте сообщение с текстом опроса',
    'create_poll_name_text': 'Отправьте сообщение с названием опроса',
    'user_polls_menu_text': '<b>Опросы</b>\n---------------------\nВыберите опрос или создать новый опрос',
    'user_nopolls_menu_text': '<b>Опросы</b>\n---------------------\nК сожалению нет активных опросов, вы можете создать новый опрос',
    'user_profile_menu_text': '<b>Профиль пользователя</b>\nИмя: <b>{username}</b>\nДата регистрации: <b>{datereg}</b>\n---------------------\n',
    'learn_paragraph_text': '{paragraph}',
    'test_question_menu_text': '{question}',
    'end_lerning_message': 'Обучение закончено\n{result_text}',
    'good_learn_text': 'Предлагаем пройти тестирование',
    'bad_learn_text': 'Вы прошли обучение, но есть ошибки в проверочных вопросах, вы можете повторно пройти обучение или начать тестирование',
    'user_tester_menu_text': '<b>Обучение</b>\n---------------------\nВыберите курс обучения',
    'in_group_user_see_group_menu_text': '<b>{groupname}</b>\n---------------------\nОбщее количество пользователей: <b>{users_count}</b>\nВы можете пригласить пользователей в вашу группу, просто отправьте ссылку приглашение\nСкопируйте ссылку и отправьте коллегам в Телеграм, чтобы пригласить их в ваш аккаунт:\n{refer_link}',
    'user_view_group_no_users': '<b>{groupname}</b>\n---------------------\nВоспользуйтесь ссылкой для приглашения пользователей\nСкопируйте ссылку и отправьте коллегам в Телеграм, чтобы пригласить их в ваш аккаунт:\n{refer_link}',
    'user_view_group': '<b>{groupname}</b>\n---------------------\nОбщее количество пользователей: <b>{users_count}</b>\nСкопируйте ссылку и отправьте коллегам в Телеграм, чтобы пригласить их в ваш аккаунт:\n{refer_link}',
    'create_group_message_text': 'Для создания аккаунта, отправьте сообщение с названием аккаунта',
    'choose_mnu_text': 'Работать со мной лучше со всей вашей командой.\nДля этого создайте аккаунт и пригласите коллег. Или пройдите обучение',
    'hireferaluser_message_text': 'Привет, я <b>JRobot</b> - умный корпоративный ассистент.\nЯ могу проводить обучение и опросы, ставить задачи и назначать встречи.\n<b>{refer_username}</b> пригласил вас в аккаунт компании <b>{group_name}</b>.\nВы можете ставить задачи друг другу, назначать встречи или проводить опросы.\n',
    'hiuser_message_text': 'Привет, я <b>JRobot</b> - умный корпоративный ассистент.\nЯ могу проводить обучение и опросы, ставить задачи и назначать встречи.',
    'hireferaluser_message_text_no_aprowed_acc': 'Привет, я <b>JRobot</b> - умный корпоративный ассистент.\nЯ могу проводить обучение и опросы, ставить задачи и назначать встречи.\n<b>{refer_username}</b> пригласил вас в аккаунт компании <b>{group_name}</b>.\nВы можете ставить задачи друг другу, назначать встречи или проводить опросы.\n<b>{refer_username}</b> оповещён о вашей регистрации подождите подтверждения вашей кандидатуры',
    'users_view_menu_text': '<b>Пользователи</b>\n---------------------\nОбщее количество: <b>{count}</b>',
    'nousers_view_menu_text': 'К сожалению нет приглашенных пользователей\nВоспользуйтесь ссылкой для приглашения пользователей\n{referlink}',
    'admin_users_view_text': '<b>Пользователи</b>\n---------------------\nОбщее количество: <b>{count}</b>\nСозданные аккаунты организаций: <b>{groups}</b>',
    'owner_users_view_text': '<b>Приглашенные пользователи</b>\n---------------------\nОбщее количество: <b>{count}</b>\nПрисоединенные к аккаунту организаций: <b>{groups}</b>',
    'test_end_text': 'Тестирование закончено\n----------\nПравильных ответов: {rcount}\nНеправильных ответов: {wcount}',
    'right_learn_text': 'Вы ответили правильно',
    'right_learn_text_learn_end': 'Вы ответили правильно\n------\nОбучение окончено, пройдите тестирование',
    'learn_end_text': 'Обучение окончено, пройдите тестирование',
    'whrong_learn_text': 'Вы ответили неправильно, попробуйте еще раз',
    'soso_learn_text': 'Вы отметили правильный и неправильный ответ, попробуйте еще раз или продолжите обучение',
    'soso_learn_text_no_next_question': 'Вы отметили правильный и неправильный ответ, попробуйте еще раз или закончите обучение',
    'end_learn_text': 'Обучающий курс окончен\nВы можете повторить обучение или воспользуйтесь другими функциями бота',
    'questions_hi_text': 'Это обучающий курс по работе с JRobot.\nВ полной версии вы сможете создавать такие же курсы для обучения и проверки знаний ваших сотрудников.\n--------------------\n',
    'question_learn': '<b>Вопрос: #{qnum}</b>\nКатегория: {category}\n{paragraph}',
    'learn_question': '<b>Проверочный вопрос: #{qnum}</b>\n{question}\n{answers}',
    'access_close': 'Доступ закрыт',
    'hiadmin': 'Привет админ',
    'himanager': 'Привет {username}',
}

en = {
    'settings': 'Lang / Язык',
    'en_lng_btn': 'English',
    'ru_lng_btn': 'Русский',
    'settings_menu_text': 'Выберите язык / Choose language',
    'create_acc': 'Create acc',
    'to_menu_btn': 'To the menu',
    'next': 'Forward',
    'back_p': 'Back',
    'cancel_mnu_btn': 'Cancel',
    'end_mnu_btn': 'Finish',
    'edit_name': 'Change Name',
    'edit_date': 'Change date or time',
    'edit_theme': 'Change Subject',
    'edit_users': 'Edit Members',
    'letsgo_btn': 'Start',
    'yes': 'yes',
    'no': 'No',
    'learn_mnu_btn': 'Training',
    'test_mnu_btn': 'Quiz',
    'tasks_mnu_btn': 'Tasks',
    'add_task_to_user': 'Set task',
    'user_creator_task_btn': 'Tasks created by you',
    'im_do_this_task': 'Accept',
    'fuck_this_task': 'Reject',
    'close_task_mnu_btn': 'Comlete',
    'end_tasks_mnu_btn': 'Completed Tasks',
    'polls_mnu_btn': 'Polls',
    'add_poll_mnu_btn': 'Create poll',
    'arch_polls': 'Archived polls',
    'end_poll': 'Comlete',
    'meet_mnu_btn': 'Meetings',
    'create_group_mnu_btn': 'Create an account',
    'get_learn_mnu_btn': 'Start training',
    're_learn_btn': 'Repeat training',
    'users_mnu_btn': 'Users',
    'groups_view_btn': 'Accounts',
    'user_group_mnu_btn': 'Account',
    'group_owner_view_btn': 'Company account',
    'add_user_to_refer': 'Invite user',
    'test_question': 'Test question',
    'cheked': '✅',
    'nocheked': '',
    'answer_btn': '{number} {chk}',
    'test_chek_answer_btn': 'Check answer',
    'next_learn_question_btn': 'Next question',
    'end_learn_question_btn': 'Complete your training',
    'learn_curs_btn': '{curs_name}',
    'create_forum_mnu_btn': 'Schedule a meeting',
    'end_forum_mnu_btn': 'Completed Meetings',
    'now_date': 'Today',
    'tomorrow_date': 'Tomorrow',
    'to_week_day': 'In a week',
    'add_date': 'Enter manually',
    'create_forum_end_btn': 'Schedule a meeting',
    'edit_forum_users_end': 'Complete Editing',
    'aprowe_btn': 'Confirm',
    'cancel_reg': 'Reject',
    'view_task': 'View Task',
    'add_forum_comment': 'Summarize the meeting',
    'relearn_btn': 'Repeat training',
    'acc_not_created': 'Acc is not created',
    'bad_test_text': '\n---------------------\nTest failed, we recommend to repeat training',
    'forum_ended_head': 'The meeting is over\n',
    'forum_details_text_alert_15_min': '<b>The meeting will start in 15 minutes:\n{forum_name}</b>\n---------------------\nCreator of the meeting: <b> {username}</b>\nCreation Date: <b>{date_create}</b>\nDate and Start Time: <b>{date_start}</b>\nDuration: <b>{time_delta} </b>\n---------------------\n{forum_theme}\n----------------------\n{users}',
    'alert_15_do_task': 'The task completion time is appropriate <b>{task_name}</b>\n---------------------\nThe task creator: <b>{creator_username }</b>\nDate of creation: <b>{date_start}</b>\nDate of completion: <b>{date_end}</b>\nDescription of the task:\n\n{task_text}',
    'alert_cancel_task': 'Task <b>{task_name}</b> rejected',
    'alert_do_task': 'Task <b>{task_name}</b> is accepted',
    'alert_close_task': 'Task <b>{task_name}</b> is completed\nComment:\n{comment}',
    'refer_aprowed_user_text': 'User registration was successfully confirmed',
    'refer_cancel_user_text': 'User Registration Rejected',
    'message_send_cancel_user_text': '<b>{refer_username}</b> has rejected your registration <b>{group_name}</b>.\nPlease create your account and invite users there, for that, click the "Account" button',
    'message_send_aprowed_user_text': '<b>{refer_username}</b> has confirmed registration with <b>{group_name}</b>.\nYou can set tasks to each other, make meetings and polls.',
    'message_send_new_referal': 'A new user is registered in the account <b>{group_name}</b>\nName: <b>{username}</b>\nRegistration Date: <b>{date_reg}</b>\n----------------------\nConfirm or reject user registration',
    'end_test_and_results_text': '<b>Testing completed</b>\n{results}',
    'forum_update_theme_text': 'Send a message with the topic of a meeting or a list of questions for discussion',
    'forum_update_name_text': 'Send a message with a new meeting name',
    'forum_end_add_comment_text': 'Send a text comment with the results of the meeting',
    'poll_create_manual_time_again_menu': '<b>Poll completion time</b>\nThere was an error adding polling end time, try again\nSend a message with polling end time\nFor example: <b>14:35</b>',
    'poll_create_manual_time_menu': '<b>Poll completion time</b>\nSend a message with polling completion time\nFor example: <b>14:35</b>',
    'poll_create_time_text': '<b>Poll end time</b>\nSelect the end time of the poll',
    'poll_create_get_date': '<b>Date of completion of the survey</b>\nSelect the date of completion of the poll',
    'task_create_manual_time_again_menu': '<b>Task completion time</b>\nThere was an error adding task completion time, try again\nSend a message with task completion time\nFor example: <b>14:35</b>',
    'task_create_manual_time_menu': '<b>Task completion time</b>\nSend a message with the task completion time\nFor example: <b>14:35</b>',
    'task_create_time_text': '<b>Task completion time</b>\nSelect the task completion time',
    'task_create_get_date': '<b>Task Completion Date</b>\nSelect the task completion date',
    'forum_create_manual_time_agian_menu': '<b>{forum_name}</b>\nThere was an error adding the meeting time, try again\nSend a message with the meeting start time\nFor example: <b>09:35</b>',
    'forum_create_manual_time_menu': '<b>{forum_name}</b>\nSend a message with the start time of the meeting\nFor example: <b>09:35</b>',
    'forum_create_delta_time': '<b>{forum_name}</b>\nSpecify the approximate duration of the meeting',
    'forum_create_theme_text': '<b>{forum_name}</b>\nSend a message with the subject of a meeting or a list of questions for discussion',
    'forum_add_users': '<b>{forum_name}</b>\nSelect users to invite them to the meeting',
    'forum_add_users_nousers': 'Unfortunately there are no users to invite them to the meeting',
    'forum_create_time_text': '<b>{forum_name}</b>\nSelect the time to start the meeting',
    'forum_create_date_text_again': '<b>{forum_name}</b>\nYou made a mistake when sending a date, try again\nSend the start date of the meeting, for example: <b>{date_now}</b>',
    'forum_create_date_text': '<b>{forum_name}</b>\nSend the start date of the meeting',
    'forum_create_name_text': 'Send a message with the name of the meeting',
    'forum_create_get_date': '<b>{forum_name}</b>\nSelect the date of the meeting',
    'nogroup_user': 'You have not created an account\nClick "Account" button to create an account',
    'forum_details_text': '<b>{forum_name}</b>\n---------------------\nMeeting Creator: <b>{username} </ b >\nCreation Date: <b>{date_create}</b>\nDate and Start Time: <b>{date_start}</b>\nMeeting Duration: <b>{time_delta}</b>\n--- ------------------\n{forum_theme}\n---------------------\n{users }\n{comment}',
    'noclosed_forums_menu_text': '<b>Completed meetings</b>\n---------------------\nNo completed meetings',
    'noactive_forums_menu_text': '<b>Scheduled meetings</b>\n---------------------\nNo scheduled meetings',
    'closed_forums_menu_text': '<b>Completed Meetings</b>\n---------------------\nNumber: {count}',
    'active_forums_menu_text': '<b>Scheduled meetings</b>\n---------------------\nNumber: {count}',
    'forums_menu_text': '<b>Meetings</b>\n---------------------\nList with scheduled meetings',
    'noforums_menu_text': '<b>Meetings</b>\n---------------------\nUnfortunately, there are no scheduled meetings, but you can create a new one',
    'task_comment': '\n---------------------\n{comment}',
    'close_task_get_comment': 'Send a comment about the task completion',
    'task_end': 'Completed',
    'task_active': 'Active',
    'task_doing': 'Accepted',
    'task_cancel': 'Rejected',
    'user_nodoing_task_menu_text': '<b>Accepted tasks</b>\n---------------------\nNo accepted tasks',
    'user_nofucked_task_menu_text': '<b>Rejected tasks</b>\n---------------------\nNo rejected tasks',
    'user_noactive_task_menu_text': '<b>Active tasks</b>\n---------------------\nNo active tasks',
    'user_noclosed_task_menu_text': '<b>Completed Tasks</b>\n---------------------\nNo Completed Tasks',
    'user_doing_task_menu_text': '<b>Accepted  tasks</b>\n---------------------\nNumber: {task_count}',
    'user_fucked_task_menu_text': '<b>Rejected tasks</b>\n---------------------\nNumber: {task_count}',
    'user_active_task_menu_text': '<b>Active Tasks</b>\n---------------------\nNumber: {task_count}',
    'user_closed_task_menu_text': '<b>Completed tasks</b>\n---------------------\nNumber: {task_count}',
    'task_details_text': '<b>{task_name}</b>\n---------------------\nTask creator: <b>{creator_username} </ b >\nDate of creation: <b>{date_start}</b>\nDate: <b>{date_end}</b>\nStatus of the task: {status}\nDescription:\n\n{task_text} {comment}',
    'create_task_date_end_text_again': 'An error occurred while adding the task end date, try again\nSend a message with the date and time of the end of the task\nFor example: <b>{date_end}</b>',
    'create_task_date_end_text': 'Send a message with the date and time of the end of the task\nFor example: <b>{date_end}</b>',
    'create_task_text_text': 'Send a message with a description of the task',
    'create_task_name_text': 'Send a message with the name of the task',
    'user_select_user_to_add_task_nousers': '<b>{groupname}</b>\n---------------------\nUnfortunately, there are no other users in your account except you\nTo use link to invite users\nCopy the link and send to Telegram colleagues to invite them to your account:\n{refer_link}',
    'user_select_user_to_add_task': '<b>{groupname}</b>\n---------------------\nThe total number of users: <b>{users_count}</b>\nTo create a task, select the user',
    'user_task_menu_text': '<b>Tasks</b>\n---------------------\nList of tasks assigned to you',
    'user_notask_menu_text': '<b>Tasks</b>\n---------------------\nYou do not have any tasks assigned to you',
    'user_select_poll_variant_ans_text': 'You typed\n{var}\nThe poll results will be available when the poll is completed',
    'user_arch_polls_menu_text': '<b>Archive polls</b>\n---------------------\nSelect a poll to view statistics',
    'user_arch_nopolls_menu_text': '<b>Archive polls</b>\n---------------------\nUnfortunately there are no archival polls',
    'active': 'Published',
    'passive': 'In the archive',
    'poll_results': '\nPoll Results:\n{poll_results}',
    'user_polled_varname': '\nYou have chosen the option:\n{varname}',
    'create_poll_add_date_end': 'Send a message with the polling end date\nFor example: <b>{date_end}</b>',
    'create_poll_add_date_end_error': 'An error occurred while adding the polling end date\nSend a message with the polling end date\nFor example: <b>{date_end}</b>',
    'poll_detail_text': '<b>{pollname}</b>\n{polltext}\n---------------------\nDate creation: <b>{ date_create}</b>\nDate: <b>{date_end}</b>\nStatus: <b>{status}</b> {results}',
    'create_poll_poll_chooses_text': 'Send poll response options, starting each option with <b>/</b>\nFor example: / Yes / No',
    'create_poll_polltext_text': 'Send a message with the text of the poll',
    'create_poll_name_text': 'Send a message with the name of the poll',
    'user_polls_menu_text': '<b>Polls</b>\n---------------------\nSelect a poll or create a new poll',
    'user_nopolls_menu_text': '<b>Polls</b>\n---------------------\nUnfortunately there are no active polls, you can create a new poll',
    'user_profile_menu_text': '<b>User Profile</b>\nName: <b>{username}</b>\nRegistration Date: <b>{datereg}</b>\n-------- -------------\n',
    'learn_paragraph_text': '{paragraph}',
    'test_question_menu_text': '{question}',
    'end_lerning_message': 'Training completed\n{result_text}',
    'in_group_user_see_group_menu_text': '<b>{groupname}</b>\n---------------------\nThe total number of users: <b>{users_count}</b>\nYou can invite users to your group, just send an invitation link\nCopy the link and send to Telegram colleagues to invite them into your account:\n{refer_link}',
    'user_view_group_no_users': '<b>{groupname}</b>\n---------------------\nPlease use the link to invite users\nCopy the link and send to colleagues in Telegrams to invite them to your account:\n{refer_link}',
    'user_view_group': '<b>{groupname}</b>\n---------------------\nThe total number of users: <b>{users_count}</b>\nCopy the link and send to Telegram colleagues to invite them to your account:\n{refer_link}',
    'create_group_message_text': 'Send a message with the name of the account',
    'choose_mnu_text': 'It is better to work with me with your entire team.\nFor this, create an account and invite colleagues. Or get trained',
    'hireferaluser_message_text': 'Hi, I`m <b>JRobot</b>. I’m a smart corporate assistant.\nI will help you set tasks, schedule meetings and polls.\n<b>{refer_username}</b> invited you to <b>{group_name}</b>.\nYou can put task each other, schedule meeting or start poll.',
    'hireferaluser_message_text_no_aprowed_acc': 'Hi, I <b>JRobot</b> I`m a smart corporate assistant.\nI will help you set tasks, schedule meetings and polls.\n<b>{refer_username}</b> invited you to your account <b>{group_name}</b>.\nYou can put task each other, schedule meeting or start poll.\n<b>{refer_username}</b> was notified of your registration, wait for confirmation of your candidature',
    'users_view_menu_text': '<b>Users</b>\n---------------------\nTotal: <b>{count}</b>',
    'nousers_view_menu_text': 'Unfortunately there are no invited users\nUse the link to invite users\n{referlink}',
    'admin_users_view_text': '<b>Users</b>\n---------------------\nThe total number: <b>{count}</b>\nCreated accounts of organizations: <b>{groups}</b>',
    'owner_users_view_text': '<b>Invited users</b>\n---------------------\nTotal: <b>{count}</b>\nAnjoined account organizations: <b>{groups}</b>',
    'access_close': 'Access denied',
    'hiadmin': 'Hi admin',
    'himanager': 'Hello {username}',
}
